package com.springboot.whb.study.modules.seckill.po;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Timestamp;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table seckill
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Entity
@Table(name = "seckill")
public class Seckill implements Serializable {

    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * 商品库存id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "seckill_id", nullable = false)
    private Long seckillId;

    /**
     * Database Column Remarks:
     * 商品名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     * 库存数量
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * Database Column Remarks:
     * 秒杀开启时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_time
     *
     * @mbg.generated
     */
    private Timestamp startTime;

    /**
     * Database Column Remarks:
     * 秒杀结束时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_time
     *
     * @mbg.generated
     */
    private Timestamp endTime;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbg.generated
     */
    private Timestamp createTime;

    /**
     * Database Column Remarks:
     * 版本号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.version
     *
     * @mbg.generated
     */
    @Version
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     * @mbg.generated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     * @mbg.generated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.name
     *
     * @return the value of seckill.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.name
     *
     * @param name the value for seckill.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.number
     *
     * @return the value of seckill.number
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.number
     *
     * @param number the value for seckill.number
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_time
     *
     * @return the value of seckill.start_time
     * @mbg.generated
     */
    public Timestamp getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_time
     *
     * @param startTime the value for seckill.start_time
     * @mbg.generated
     */
    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_time
     *
     * @return the value of seckill.end_time
     * @mbg.generated
     */
    public Timestamp getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_time
     *
     * @param endTime the value for seckill.end_time
     * @mbg.generated
     */
    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     * @mbg.generated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     * @mbg.generated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.version
     *
     * @return the value of seckill.version
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.version
     *
     * @param version the value for seckill.version
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}