package com.springboot.whb.study.modules.seckill.po;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table success_killed
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Entity
@Table(name = "success_killed")
public class SuccessKilled implements Serializable {

    private static final long serialVersionUID = 1L;
    /**
     * Database Column Remarks:
     * 秒杀商品id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.seckill_id
     *
     * @mbg.generated
     */
    @Id
    @Column(name = "seckill_id", nullable = false)
    private Long seckillId;

    /**
     * Database Column Remarks:
     * 用户Id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.user_id
     *
     * @mbg.generated
     */
    @Id
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.seckill_id
     *
     * @return the value of success_killed.seckill_id
     * @mbg.generated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.seckill_id
     *
     * @param seckillId the value for success_killed.seckill_id
     * @mbg.generated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.user_id
     *
     * @return the value of success_killed.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.user_id
     *
     * @param userId the value for success_killed.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}